### ISSUE TITLE
Doesn't work with a JSON field?

### ISSUE THREAD

**Issue by flatcapco** [Comodolab/nova-help#11]
Thanks for this component - but I have a small issue: I have a prices column which is set to JSON in the database and cast as an Object on my resource.

If I make this field:

            Help::make()->message(function () {
                return $this->prices->gbp->comment;
            }),

I get an error 'trying to get property 'gbp' of none object'

However the help field shows as expected and dd($this->prices) or further clearly shows it as an object and I'm using it fine in this way on other nova fields.

I'm afraid I don't know how to debug it further sorry

Thanks

**Comment by micc83** [comment]
Hello @latwelve,

I've just tried to reproduce the error but I get the desidered result:

```php
// myjson value (JSON column): {"gbp": {"comment": "Ciao Mondo!!!"}}

// Model
protected $casts = [
        'myjson'            => 'object'
];

// Field
Help::info('Help title', function () {
    return $this->myjson->gbp->comment;
}),
```
Laravel v7, Nova 3.5.0

![image](https://user-images.githubusercontent.com/1750404/81692465-bacc2880-945e-11ea-98c9-5aa15f3e6bc3.png)

I guess it's probably something else. Reopen the ticket if you think I'm missing something.
