### ISSUE TITLE
Make help title/messages collapsable

### ISSUE THREAD

**Issue by atmediauk** [Comodolab/nova-help#16]
Hello,

I was wondering if it is possible to make the messages collapsable. For example the title would always be displayed but when it is clicked it shows/ hides the message section. This would be great for providing unintrusive assistance to the user.

It could work like Bootstraps collapse does - https://getbootstrap.com/docs/4.3/components/collapse/#example

Thanks for your time.

**Comment by micc83** [comment]
Hello @atmediauk,

I did implement collapsible help fields. Can you try it and let me know what you think?

```shell script
composer require comodolab/nova-help:dev-develop
```

**Comment by micc83** [comment]
@atmediauk were you able to test the implementation?
