### ISSUE TITLE
Display as html only works on message but not title

### ISSUE THREAD

**Issue by tobeycodes** [Comodolab/nova-help#4]

**Comment by micc83** [comment]
I'll check it out, thank you

**Comment by tobeycodes** [comment]
To achieve what I wanted I ended up using the following. Thanks for this useful repo!

```
Help::header()
  ->message('<div class="h-8 flex items-center justify-center font-bold text-90 text-lg">Personal Information</div>')
  ->icon('<div class="rounded-full font-bold text-90 border-90 border-2 w-8 h-8 flex items-center justify-center">1</div>')
  ->displayAsHtml(),
```

**Comment by sjess** [comment]
Even the example above is not working. Will there be a fix?

**Comment by tobeycodes** [comment]
@sjess what does not work about it? I use it in a production project and the html renders for both functions

**Comment by micc83** [comment]
Hello guys, I'm pretty busy lately, could you open a PR?
