### ISSUE TITLE
If the first field is a Help field on view there is a blank space

### ISSUE THREAD

**Issue by tobeycodes** [Comodolab/nova-help#5]
I am not sure if this issue is fixable within this repo but I think it's worth flagging anyway as an issue.

<img width="1410" alt="screenshot 2018-12-24 10 28 56" src="https://user-images.githubusercontent.com/3613405/50402767-f16caa80-0766-11e9-9ddb-7ceb33c19ffa.png">

**Comment by timcv** [comment]
I have the same problem. It looks nice if i put the field last, but i get the space when i put the field first.

**Comment by micc83** [comment]
Just checked on the last version and it doesn't look like this is an issue anymore.
<img width="999" alt="Schermata 2020-03-04 alle 10 08 31" src="https://user-images.githubusercontent.com/1750404/75863022-1d220080-5e00-11ea-9d7f-8b0237d647cb.png">
